//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaPha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int ID { get; set; }
        public string AnhDongHo { get; set; }
        public string AnhThanhVien { get; set; }
    }
}
