//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaPha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public Nullable<int> NamMat { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> VoChong { get; set; }
        public string DiaPhuong { get; set; }
        public string LyLich { get; set; }
        public string Avt { get; set; }
        public Nullable<bool> IsTruongHo { get; set; }
        public Nullable<bool> IsTruongChi { get; set; }
    
        public virtual VoChong VoChong1 { get; set; }
    }
}
